In [107]:
import pandas as pd

In [108]:
tournament_data= pd.read_csv('tournaments.csv')
bookings_data= pd.read_csv('bookings.csv')

In [109]:
#bookings_data=bookings_data[['tournament_id', 'team_name', 'booking_id', 'minute_regulation','yellow_card', 'red_card' , 'second_yellow_card']].head(2)
bookings_data

,key_id,booking_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,given_name,shirt_number,minute_label,minute_regulation,minute_stoppage,match_period,yellow_card,red_card,second_yellow_card,sending_off
0,1,B-0001,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-69,...,Kakhi,11,30',30,0,first half,1,0,0,0
1,2,B-0002,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-69,...,Givi,19,31',31,0,first half,1,0,0,0
2,3,B-0003,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-69,...,Evgeny,6,34',34,0,first half,1,0,0,0
3,4,B-0004,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,...,Gustavo,3,60',60,0,second half,1,0,0,0
4,5,B-0005,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-69,...,Gennady,7,72',72,0,second half,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2461,2462,B-2462,WC-2018,2018 FIFA World Cup,M-2018-63,Belgium v England,2018-07-14,third-place match,not applicable,T-27,...,Harry,6,76',76,0,second half,1,0,0,0
2462,2463,B-2463,WC-2018,2018 FIFA World Cup,M-2018-63,Belgium v England,2018-07-14,third-place match,not applicable,T-06,...,Axel,6,90'+3',90,3,"second half, stoppage time",1,0,0,0
2463,2464,B-2464,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-28,...,N'Golo,13,27',27,0,first half,1,0,0,0
2464,2465,B-2465,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-28,...,Lucas,21,41',41,0,first half,1,0,0,0
2465,2466,B-2466,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,...,Šime,2,90'+2',90,2,"second half, stoppage time",1,0,0,0

In [110]:
#tournament_data=tournament_data[['tournament_id', 'winner']].head(2)
tournament_data=tournament_data.rename(columns={'winner': 'team_name'})
tournament_data

,key_id,tournament_id,tournament_name,year,start_date,end_date,host_country,team_name,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,1,WC-1930,1930 FIFA World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,2,WC-1934,1934 FIFA World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,3,WC-1938,1938 FIFA World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1
3,4,WC-1950,1950 FIFA World Cup,1950,1950-06-24,1950-07-16,Brazil,Uruguay,0,13,1,0,1,0,0,0,0,0
4,5,WC-1954,1954 FIFA World Cup,1954,1954-06-16,1954-07-04,Switzerland,West Germany,0,16,1,0,0,0,1,1,1,1
5,6,WC-1958,1958 FIFA World Cup,1958,1958-06-08,1958-06-29,Sweden,Brazil,0,16,1,0,0,0,1,1,1,1
6,7,WC-1962,1962 FIFA World Cup,1962,1962-05-30,1962-07-17,Chile,Brazil,0,16,1,0,0,0,1,1,1,1
7,8,WC-1966,1966 FIFA World Cup,1966,1966-07-11,1966-07-30,England,England,1,16,1,0,0,0,1,1,1,1
8,9,WC-1970,1970 FIFA World Cup,1970,1970-05-31,1970-06-21,Mexico,Brazil,0,16,1,0,0,0,1,1,1,1
9,10,WC-1974,1974 FIFA World Cup,1974,1974-06-13,1974-07-07,West Germany,West Germany,1,16,1,1,0,0,0,0,1,1
10,11,WC-1978,1978 FIFA World Cup,1978,1978-06-01,1978-06-25,Argentina,Argentina,1,16,1,1,0,0,0,0,1,1
11,12,WC-1982,1982 FIFA World Cup,1982,1982-06-13,1982-07-11,Spain,Italy,0,24,1,1,0,0,0,1,1,1
12,13,WC-1986,1986 FIFA World Cup,1986,1986-05-31,1986-06-29,Mexico,Argentina,0,24,1,0,0,1,1,1,1,1
13,14,WC-1990,1990 FIFA World Cup,1990,1990-06-08,1990-07-08,Italy,West Germany,0,24,1,0,0,1,1,1,1,1
14,15,WC-1994,1994 FIFA World Cup,1994,1994-06-17,1994-07-17,United States,Brazil,0,24,1,0,0,1,1,1,1,1
15,16,WC-1998,1998 FIFA World Cup,1998,1998-06-10,1998-07-12,France,France,1,32,1,0,0,1,1,1,1,1
16,17,WC-2002,2002 FIFA World Cup,2002,2002-05-31,2002-06-30,"Korea, Japan",Brazil,0,32,1,0,0,1,1,1,1,1
17,18,WC-2006,2006 FIFA World Cup,2006,2006-06-09,2006-07-09,Germany,Italy,0,32,1,0,0,1,1,1,1,1
18,19,WC-2010,2010 FIFA World Cup,2010,2010-06-11,2010-07-11,South Africa,Spain,0,32,1,0,0,1,1,1,1,1
19,20,WC-2014,2014 FIFA World Cup,2014,2014-06-12,2014-07-13,Brazil,Germany,0,32,1,0,0,1,1,1,1,1
20,21,WC-2018,2018 FIFA World Cup,2018,2018-06-14,2018-07-15,Russia,France,0,32,1,0,0,1,1,1,1,1

In [111]:
winner_booking_info=pd.merge(tournament_data, bookings_data, on= ['tournament_id', 'team_name'])
winner_booking_info[['tournament_id','team_name', 'yellow_card', 'red_card']]
winner_booking_info.groupby(['tournament_id','team_name']).agg({'yellow_card': 'sum', 'red_card': 'sum'}).reset_index()

   tournament_id     team_name  yellow_card  red_card
0        WC-1970        Brazil            3         0
1        WC-1974  West Germany            3         0
2        WC-1978     Argentina            4         0
3        WC-1982         Italy           11         0
4        WC-1986     Argentina           12         0
5        WC-1990  West Germany            8         1
6        WC-1994        Brazil            8         1
7        WC-1998        France           13         2
8        WC-2002        Brazil            7         1
9        WC-2006         Italy           11         2
10       WC-2010         Spain            8         0
11       WC-2014       Germany            6         0
12       WC-2018        France           12         0

In [118]:
non_winner_booking_info=pd.merge(tournament_data[ [ 'tournament_id', 'team_name' ] ], \
                                 bookings_data, how='outer', on=['tournament_id', 'team_name'], \
                                 indicator=True)

non_winner_booking_info=non_winner_booking_info.loc[non_winner_booking_info['_merge']== 'right_only']
non_winner_booking_info[['tournament_id','team_name', 'yellow_card', 'red_card']]
non_winner_booking_info.groupby(['tournament_id','team_name']).agg({'yellow_card': 'sum', 'red_card': 'sum'}).reset_index()

    tournament_id       team_name  yellow_card  red_card
0         WC-1970         Belgium          3.0       0.0
1         WC-1970  Czechoslovakia          2.0       0.0
2         WC-1970     El Salvador          4.0       0.0
3         WC-1970         England          2.0       0.0
4         WC-1970          Israel          4.0       0.0
..            ...             ...          ...       ...
312       WC-2018           Spain          2.0       0.0
313       WC-2018          Sweden          8.0       0.0
314       WC-2018     Switzerland          9.0       1.0
315       WC-2018         Tunisia          4.0       0.0
316       WC-2018         Uruguay          3.0       0.0

[317 rows x 4 columns]